export const products = [
  {
    id: 0,
    name: 'Xiaomi G34Qi Monitor',
    specs: '24 Inch',
    description: 'gaming curved 24 inches',
    price: 5699,
    category: 'pcparts',
    image: './Images/xiaomi monitor.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 1,
    name: 'Acer Nitro Monitor',
    specs: '23.8',
    description: 'Widescreen IPS Monitor.',
    price: 6845,
    category: 'pcparts',
    image: './Images/acermonitor.jpg',
    quantity: 'per pick',
  },
  {
    id: 2,
    name: 'Samsung LS24C330',
    specs: '24 Inch',
    description: 'Gaming Monitor',
    price: 5899,
    category: 'pcparts',
    image: './Images/samsungmonitor.jpg',
    quantity: 'per pick',
  },
  {
    id: 3,
    name: 'Dell S3222HG',
    specs: '32 Inch',
    description: 'Curve Gaming Monitor',
    price: 63617,
    category: 'pcparts',
    image: './Images/dellmonitor.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 4,
    name: 'Asus TUF VG249Q',
    specs: '23.8',
    description: '23.8-inch ASUS TUF gaming monitor.',
    price: 7146,
    category: 'pcparts',
    image: './Images/asusmonitor.jpg',
    quantity: 'per pick',
  },
  {
    id: 5,
    name: 'Icon Monitor',
    specs: '22 Inch',
    description: 'Rimless Gaming Monitor.',
    price: 2120,
    category: 'pcparts',
    image: './Images/iconmonitor.jpg',
    quantity: 'per pick',
  },
  {
    id: 6,
    name: 'Logitech KBoard',
    specs: 'Multi-Device',
    description: 'Logitech wireless keyboard.',
    price: 1690,
    category: 'pcparts',
    image: './Images/keyboard1.jpg',
    quantity: 'per pick',
  },
  {
    id: 7,
    name: 'Redragon K568',
    specs: 'Mech KBoard',
    description: 'Dark Avenger.',
    price: 4876,
    category: 'pcparts',
    image: './Images/keyboard2.jpg',
    quantity: 'per pick',
  },
  {
    id: 8,
    name: 'HyperX Allou KB',
    specs: 'Gaming KB',
    description: '60 Wired Gaming Keyboard.',
    price: 5930,
    category: 'pcparts',
    image: './Images/keyboard3.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 9,
    name: 'Razer Huntsman',
    specs: 'Mini 60',
    description: 'Fast Switch Keyboard',
    price: 7849,
    category: 'pcparts',
    image: './Images/keyboard4.jpg',
    quantity: 'per pick',
  },
  {
    id: 10,
    name: 'Logitech G512',
    specs: 'RGB MECH KB',
    description: 'GX mechanical switches.',
    price: 6345,
    category: 'pcparts',
    image: './Images/keyboard5.jpg',
    quantity: 'per pick',
  },
  {
    id: 11,
    name: 'Aula N-69 Speaker',
    specs: 'RGB',
    description: 'RGB DESKTOP SPEAKER 2.0.',
    price: 315,
    category: 'pcparts',
    image: './Images/speaker1.jpg',
    quantity: 'per pick',
  },
  {
    id: 12,
    name: 'REDRAGON Orpheus',
    specs: 'GS550',
    description: 'The maneuverable size of GS550.',
    price: 900,
    category: 'pcparts',
    image: './Images/speaker2.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 13,
    name: 'HP DHE-6000',
    specs: 'Speaker',
    description: 'Description High-quality HP stereo.',
    price: 445,
    category: 'pcparts',
    image: './Images/speaker3.jpg',
    quantity: 'per pick',
  },
  {
    id: 14,
    name: 'G102 RGB Mouse',
    specs: 'Mouse',
    description: 'G102 designed for gamers.',
    price: 175,
    category: 'pcparts',
    image: './Images/mouse1.jpg',
    quantity: 'per pick',
  },
  {
    id: 15,
    name: 'HP M160 Wired',
    specs: 'Gaming',
    description: 'Optical Sensor for PC/Laptop.',
    price: 1786,
    category: 'pcparts',
    image: './Images/mouse2.jpg',
    quantity: 'per pick',
  },
  {
    id: 16,
    name: 'Razer Deathadder',
    specs: 'Mouse',
    description: 'About Razer For Gamers.',
    price: 995,
    category: 'pcaprts',
    image: './Images/mouse3.jpg',
    quantity: 'per pick',
  },
  {
    id: 17,
    name: 'INPLAY CASE',
    specs: 'Cpu Case',
    description: 'Tempered Glass With Dust filter.',
    price: 615,
    category: 'pcparts',
    onSale: true,
    image: './Images/case1.jpg',
    quantity: 'per pick',
  },
  {
    id: 18,
    name: 'Pure Base 500',
    specs: 'Case',
    description: 'Tower Case Windows.',
    price: 5230,
    category: 'pcparts',
    image: './Images/case2.jpg',
    quantity: 'per pick',
  },
  {
    id: 19,
    name: 'NZXT H series',
    specs: 'Case',
    description: 'NZXT H9 Flow ATX Mid-Tower.',
    price: 8295,
    category: 'pcparts',
    image: './Images/case3.jpg',
    quantity: 'per pick',
  },
  {
    id: 20,
    name: 'MonTeCH Air PC Tower',
    specs: 'Case',
    description: 'Flagship Model from the AIR series.',
    price: 4878,
    category: 'pcparts',
    image: './Images/case4.jpg',
    quantity: 'per pick',
  },
  {
    id: 21,
    name: 'MKEPS Gaming',
    specs: 'Headset',
    description: 'LED Wireless Gaming Headset.',
    price: 319,
    category: 'pcaprts',
    image: './Images/headset1.jpg',
    quantity: 'per pick',
  },
  {
    id: 22,
    name: 'Logitech G435',
    specs: 'Headset',
    description: 'Wireless Gaming Headset.',
    price: 3196,
    category: 'pcparts',
    image: './Images/headset2.jpg',
    quantity: 'per pick',
  },
  {
    id: 23,
    name: 'FanTech USB',
    specs: 'Headset',
    description: 'Fantech CAPTAIN HG11.',
    price: 1920,
    category: 'pcparts',
    image: './Images/headset3.jpg',
    quantity: 'per pick',
  },
  {
    id: 24,
    name: 'JBL Quantum',
    specs: 'Headset',
    description: 'Turn your game into an epic event.',
    price: 1799,
    onSale: true,
    category: 'pcparts',
    image: './Images/headset4.jpg',
    quantity: 'per pick',
  },
  {
    id: 25,
    name: 'Steelseries',
    specs: 'Mouse Pad',
    description: 'faster mouse movements.',
    price: 35,
    category: 'pcparts',
    image: './Images/mousepad1.jpg',
    quantity: 'per pick',
  },
  {
    id: 26,
    name: 'TYLEX XW360',
    specs: 'Mouse Pad',
    description: 'The TYLEX XW360 Gaming Mouse.',
    price: 155,
    category: 'pcparts',
    image: './Images/mousepad2.jpg',
    quantity: 'per pick',
  },
  {
    id: 27,
    name: 'Tamee Webcam',
    specs: 'Webcam',
    description: 'TAMEE Webcam for PC Laptop 2K.',
    price: 215,
    category: 'pcparts',
    image: './Images/cam1.jpg',
    quantity: 'per pick',
  },
  {
    id: 28,
    name: 'Logitech Brio 4k',
    specs: 'Webcam',
    description: 'Premium 4K webcam with HDR.',
    price: 8430,
    onSale: true,
    category: 'pcparts',
    image: './Images/cam2.jpg',
    quantity: 'per pick',
  },
  {
    id: 29,
    name: 'SecretLLAB Superman',
    specs: 'GChair',
    description: 'Secretlab TITAN Evo Superman.',
    price: 5533,
    category: 'pcparts',
    image: './Images/chair1.jpg',
    quantity: 'per pick',
  },
  {
    id: 30,
    name: 'HUVUDSPLERE',
    specs: 'GChair',
    description: 'Adjust the angle to sit really comfortably.',
    price: 2667,
    category: 'pcparts',
    image: './Images/chair2.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 31,
    name: 'ASUS ROG Chariot',
    specs: 'GChair',
    description: 'Gaming chair in racing-car style.',
    price: 20105,
    category: 'Fruits',
    image: './Images/chair3.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 32,
    name: 'Ryzen 5600',
    specs: 'CPU Unit',
    description: 'Windows 10 Home 64.',
    price: 7890,
    category: 'pcbuilds',
    image: './Images/build1.jpg',
    quantity: 'per pick',
  },
  {
    id: 33,
    name: 'AMD Ryzen 5600X',
    specs: 'CPU Unit',
    description: 'Nvidia GTX 7600.',
    price: 14890,
    category: 'pcbuilds',
    image: './Images/build2.jpg',
    quantity: 'per pick',
  },
  {
    id: 34,
    name: 'Ryzen 7 5700X',
    specs: 'CPU Unit',
    description: '16gb RAM 500gb NVME SSD.',
    price: 5700,
    category: 'pcbuilds',
    image: './Images/build3.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 35,
    name: 'Intel Core i5-13400',
    specs: 'CPU',
    description: '13th generation Desktop.',
    price: 20890,
    category: 'pcbuilds',
    image: './Images/build4.jpg',
    quantity: 'per pick',
  },
  {
    id: 36,
    name: 'Office Desktop',
    specs: 'Full Set',
    description: 'Intel Core i7 13th Gen.',
    price: 61136,
    category: 'pcbuilds',
    image: './Images/build5.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 37,
    name: 'Dell Vostro',
    specs: 'CPU Unit',
    description: 'Intel i5 8GB 512GB SSD.',
    price: 15180,
    category: 'pcbuilds',
    image: './Images/build6.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 38,
    name: 'Genisis Brazer',
    specs: 'CPU Unit',
    description: 'Ryzen 7 5700X.',
    price: 15900,
    category: 'pcbuilds',
    image: './Images/build7.jpg',
    quantity: 'per pick',
  },
  {
    id: 39,
    name: 'Office PC',
    specs: 'Intel Core i7-12700',
    description: 'Hairy fruit with juicy sweet flesh.',
    price: 45813,
    category: 'pcbuilds',
    image: './Images/build8.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 40,
    name: 'AMD Ryzen 78003XD',
    specs: 'Processor',
    description: 'Ryzen 78003XD (w/cooler).',
    price: 10150,
    category: 'processors',
    image: './Images/proc1.jpg',
    quantity: 'per pick',
  },
  {
    id: 41,
    name: 'AMD Ryzen 5 5600X',
    specs: 'Processor',
    description: 'Leafy green vegetable rich in iron.',
    price: 5730,
    category: 'processors',
    image: './Images/proc2.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 42,
    name: 'Intel i7 13th Gen',
    specs: 'Processor',
    description: 'powerful addition to the Intel lineup.',
    price: 24900,
    category: 'processors',
    image: './Images/proc3.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 43,
    name: 'AMD Ryzen 3',
    specs: 'Processor',
    description: 'Experience seamless performance.',
    price: 3695,
    category: 'processors',
    image: './Images/proc4.jpg',
    quantity: 'per pick',
  },
  {
    id: 44,
    name: 'Intel Core i9',
    specs: 'Processor',
    description: 'Introducing the game-changing Intel i9.',
    price: 36748,
    category: 'processors',
    image: './Images/proc5.jpg',
    quantity: 'per pick',
  },
  {
    id: 45,
    name: 'Intel i3 10 Gen',
    specs: 'Processor',
    description: 'The Core i3-10100 3. 6 GHz Quad-Core.',
    price: 17452,
    category: 'processors',
    image: './Images/proc6.jpg',
    quantity: 'per pick',
  },
  {
    id: 46,
    name: 'AMD Ryzen 7',
    specs: 'Processor',
    description: 'Damn, That you want it.',
    price: 20850,
    category: 'processors',
    image: './Images/proc7.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 47,
    name: 'Intel Core i5',
    specs: 'Processor',
    description: 'Intel Core 12th Gen i5-12400 LGS1700.',
    price: 14540,
    category: 'processors',
    image: './Images/proc8.jpg',
    quantity: 'per pick',
  },
  {
    id: 48,
    name: 'Intel Core i6',
    specs: 'Processor',
    description: 'high-quality processor.',
    price: 14088,
    category: 'processors',
    image: './Images/proc9.jpg',
    quantity: 'per pick',
  },
  {
    id: 49,
    name: 'Intel Xeon 8-Core',
    specs: 'Processor',
    description: 'Server Processor Product.',
    price: 17629,
    category: 'processors',
    image: './Images/proc10.jpg',
    quantity: 'per pick',
  },
  {
    id: 50,
    name: 'Gigabyte RTX 3070',
    specs: 'GCard',
    description: 'GeForce RTX 3060',
    price: 22999,
    category: 'gcards',
    image: './Images/gcard1.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 51,
    name: 'MSI GeForce RTX 3050',
    specs: 'GCard',
    description: 'brings a performance-focused design.',
    price: 34749,
    category: 'gcards',
    image: './Images/gcard2.jpg',
    quantity: 'per pick',
  },
  {
    id: 52,
    name: 'MSI GT 710',
    specs: 'GCard',
    description: 'msi NVIDIA GeForce GT 710 graphic card.',
    price: 17629,
    category: 'gcards',
    image: './Images/gcard3.jpg',
    quantity: 'per pick',
  },
  {
    id: 53,
    name: 'MSI RTX 4060ti',
    specs: 'GCard',
    description: 'Complete graphical subsystem of the PC.',
    price: 25295,
    category: 'gcards',
    image: './Images/gcard4.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 54,
    name: 'Gigabyte RTX 4060',
    specs: 'GCard',
    description: 'optimal iteration of NVIDIA.',
    price: 19595,
    category: 'gcards',
    image: './Images/gcard5.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 55,
    name: 'MSI GTX 1660',
    specs: 'GCard',
    description: 'The MSI GTX 1660 Super Gaming.',
    price: 9456,
    category: 'gcards',
    image: './Images/gcard6.jpg',
    quantity: 'per pick',
  },
  {
    id: 56,
    name: 'ASUS DUAL RTX 3050',
    specs: 'GCard',
    description: 'NVIDIA Ampere Streaming Multiprocessors.',
    price: 11995,
    category: 'gcards',
    image: './Images/gcard7.jpg',
    quantity: 'per pick',
  },
  {
    id: 57,
    name: 'Intel Arc A750',
    specs: 'GCard',
    description: 'The Arc A750 Graphics Single from Intel.',
    price: 16995,
    category: 'gcards',
    image: './Images/gcard8.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 58,
    name: 'NVIDIA RTX 5070',
    specs: 'GCard',
    description: 'Powered by AI DLSS is a revolutionary.',
    price: 61595,
    category: 'gcards',
    image: './Images/gcard10.jpg',
    quantity: 'per pick',
  },
  {
    id: 59,
    name: 'NVIDIA RTX 5080',
    specs: 'GCard',
    description: 'Powered by AI DLSS4 is a revolutionary.',
    price: 105646,
    category: 'gcards',
    image: './Images/gcard10.jpg',
    quantity: 'per pick',
  },
  {
    id: 60,
    name: 'ROG STRIX RTX 3050',
    specs: 'GCard',
    description: 'The ROG Strix GeForce RTX 3070.',
    price: 397574,
    category: 'gcards',
    image: './Images/gcard11.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 61,
    name: 'Razer Blade 15',
    specs: 'Laptop',
    description: 'The Advanced Model of the Razer Blade.',
    price: 291874,
    category: 'lappy',
    image: './Images/lap1.jpg',
    quantity: 'per pick',
  },
  {
    id: 62,
    name: 'NingMei 15 Intel',
    specs: 'Laptop',
    description: 'NL100P Processor Brand: Intel.',
    price: 15999,
    category: 'lappy',
    image: './Images/lap2.jpg',
    quantity: 'per pick',
  },
  {
    id: 63,
    name: 'Acer Nitro V',
    specs: 'Laptop',
    description: 'Acer Nitro V Gaming Laptop.',
    price: 43969,
    category: 'lappy',
    image: './Images/lap3.jpg',
    quantity: 'per pick',
  },
  {
    id: 63,
    name: 'Acer Acespire 3',
    specs: 'Laptop',
    description: 'Creativity Powerful and portable.',
    price: 10969,
    category: 'lappy',
    image: './Images/lap4.jpg',
    quantity: 'per pick',
    onSale: true,
  },
  {
    id: 64,
    name: 'HP 250 G9',
    specs: 'Laptop',
    description: 'Creativity Powerful and portable.',
    price: 25995,
    category: 'lappy',
    image: './Images/lap5.jpg',
    quantity: 'per pick',
  },
  {
    id: 65,
    name: 'ASUS Vivobook 14',
    specs: 'Laptop',
    description: 'a notebook designed for productivity.',
    price: 34995,
    category: 'lappy',
    image: './Images/lap6.jpg',
    quantity: 'per pick',
    onSale: true,
  },
];
